#!/usr/bin/env python3
"""Bake Departure Mono Tight into a table of 6 x 12 bitmaps for the Q kit.

    plugins/tools/gen_glyphs.py [FONT.ttf] [--out plugins/quadrille.bar/Q/Glyphs.js]

Why bitmaps and not a font. Departure Mono is a pixel font: at its native em
(11) one font pixel is one pixel. On a screen whose scale is not a whole number
(eDP-2 at 1.666667) a Qt Text cannot be set at the size that makes one font
pixel a whole number of device pixels: QML's pixel size is an integer, and a
point size is rounded to one before the font engine sees it. At 20 logical px
the font is rasterised at 33.33 device px, edges land between pixels, and the
result is anti-aliased fringes and unequal stems. A bitmap drawn as rectangles
is whole device pixels at any scale, by construction.

Each glyph is rendered with FreeType at 11 px, 1 bit, with the baseline on row
10 of a 12-row cell (cap tops on row 2: quadrille's `Face::BODY`), and stored as
twelve rows of seven bits, two hex digits a row: the cell is six columns wide,
and a few glyphs (# % & } and some Latin) have a seventh pixel that hangs over
into the next cell's empty left side, as they do in the font. Codepoints:
whatever the font has in Latin, punctuation, arrows, box drawing and blocks.
"""
import argparse
import sys
from pathlib import Path

from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent
DEFAULT_FONTS = [
    Path.home() / ".local/share/fonts/departure-mono/DepartureMonoTight-Regular.ttf",
    HERE.parent.parent.parent / "quadrille/crates/quadrille/fonts/DepartureMonoTight-Regular.ttf",
    HERE.parent.parent.parent / "graticule/crates/quadrille/fonts/DepartureMonoTight-Regular.ttf",
]
RANGES = [
    (0x20, 0x7E), (0xA0, 0xFF), (0x100, 0x17F), (0x2010, 0x2027), (0x2030, 0x203A),
    (0x2190, 0x21FF), (0x2500, 0x259F), (0x25A0, 0x25FF), (0x2022, 0x2022),
]
CELL, COLS, ROWS, BASELINE = 6, 7, 12, 10


def wanted(cmap):
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            if cp in cmap:
                yield cp


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("font", nargs="?")
    parser.add_argument("--out", default=str(HERE.parent / "quadrille.bar/Q/Glyphs.js"))
    args = parser.parse_args()

    path = Path(args.font) if args.font else next((p for p in DEFAULT_FONTS if p.exists()), None)
    if path is None or not path.exists():
        sys.exit("no DepartureMonoTight-Regular.ttf found; pass its path")

    cmap = TTFont(str(path)).getBestCmap()
    font = ImageFont.truetype(str(path), 11, layout_engine=ImageFont.Layout.BASIC)

    table, clipped = {}, []
    for cp in sorted(set(wanted(cmap))):
        image = Image.new("1", (COLS + 6, ROWS), 0)
        draw = ImageDraw.Draw(image)
        draw.fontmode = "1"
        draw.text((3, BASELINE), chr(cp), font=font, fill=1, anchor="ls")
        pixels = image.load()
        rows = []
        for y in range(ROWS):
            bits = 0
            for x in range(COLS):
                if pixels[x + 3, y]:
                    bits |= 1 << (COLS - 1 - x)
            rows.append(bits)
            if any(pixels[x, y] for x in (0, 1, 2)) or any(pixels[x + 3, y] for x in range(COLS, COLS + 3)):
                clipped.append(cp)
        if any(rows):
            table[cp] = "".join(f"{r:02x}" for r in rows)
        elif chr(cp).strip() == "" or cp == 0xA0:
            table[cp] = "0" * 24

    lines = [
        "// Generated by plugins/tools/gen_glyphs.py from Departure Mono Tight: do not edit.",
        "// Twelve rows of seven bits a glyph, two hex digits a row, bit 6 the left column;",
        "// the cell is six wide, the seventh column hangs into the next cell; the",
        "// baseline is row 10. See that script for why these are bitmaps.",
        ".pragma library",
        "",
        "var cell = %d" % CELL,
        "var cols = %d" % COLS,
        "var rows = %d" % ROWS,
        "var missing = \"%s\"" % "".join(f"{b:02x}" for b in (0x3e, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x3e, 0, 0)),
        "var glyphs = {",
    ]
    items = sorted(table.items())
    for i, (cp, hexrows) in enumerate(items):
        lines.append('  "%d":"%s"%s' % (cp, hexrows, "," if i < len(items) - 1 else ""))
    lines += [
        "}",
        "",
        "// The lit runs of `text`, as { x, y, w } in pixels, left to right, one row at a",
        "// time: adjacent glyphs' pixels in a row join into one run.",
        "function runs(text) {",
        "  var chars = Array.from(String(text))",
        "  var width = chars.length * cell + (cols - cell)",
        "  var out = []",
        "  for (var y = 0; y < rows; y++) {",
        "    var lit = []",
        "    for (var a = 0; a < width; a++) lit.push(false)",
        "    for (var i = 0; i < chars.length; i++) {",
        "      var key = String(chars[i].codePointAt(0))",
        "      var hex = glyphs[key] !== undefined ? glyphs[key] : missing",
        "      var bits = parseInt(hex.substr(y * 2, 2), 16)",
        "      if (bits === 0) continue",
        "      for (var x = 0; x < cols; x++)",
        "        if ((bits >> (cols - 1 - x)) & 1) lit[i * cell + x] = true",
        "    }",
        "    var start = -1",
        "    for (var at = 0; at <= width; at++) {",
        "      var on = at < width && lit[at]",
        "      if (on && start < 0) start = at",
        "      else if (!on && start >= 0) { out.push({ x: start, y: y, w: at - start }); start = -1 }",
        "    }",
        "  }",
        "  return out",
        "}",
        "",
        "function length(text) { return Array.from(String(text)).length }",
        "",
        "// `text` wrapped to `columns` cells and at most `maxLines` lines: on spaces and",
        "// newlines, anywhere in a word longer than a line; the last line ends in an",
        "// ellipsis when text was left over.",
        "function wrap(text, columns, maxLines) {",
        "  var lines = []",
        "  var paragraphs = String(text).replace(/\\r\\n?/g, \"\\n\").split(\"\\n\")",
        "  for (var p = 0; p < paragraphs.length; p++) {",
        "    var words = paragraphs[p].split(/ +/)",
        "    var line = []",
        "    for (var w = 0; w < words.length; w++) {",
        "      var word = Array.from(words[w])",
        "      if (word.length === 0) continue",
        "      var room = columns - line.length - (line.length > 0 ? 1 : 0)",
        "      if (word.length <= room) {",
        "        if (line.length > 0) line.push(\" \")",
        "        line = line.concat(word)",
        "      } else if (word.length <= columns) {",
        "        lines.push(line.join(\"\")); line = word",
        "      } else {",
        "        if (line.length > 0) { lines.push(line.join(\"\")); line = [] }",
        "        while (word.length > columns) { lines.push(word.slice(0, columns).join(\"\")); word = word.slice(columns) }",
        "        line = word",
        "      }",
        "    }",
        "    lines.push(line.join(\"\"))",
        "  }",
        "  while (lines.length > 1 && lines[lines.length - 1] === \"\" && paragraphs[paragraphs.length - 1] === \"\") lines.pop()",
        "  if (lines.length > maxLines) {",
        "    lines = lines.slice(0, maxLines)",
        "    lines[maxLines - 1] = fit(lines[maxLines - 1] + \"\\u2026\", columns)",
        "  }",
        "  return lines",
        "}",
        "",
        "// `text` cut to `columns` cells, ending in an ellipsis when cut; a text too",
        "// long for even the ellipsis is dropped (a label cut to one letter reads as",
        "// a different label).",
        "function fit(text, columns) {",
        "  var chars = Array.from(String(text))",
        "  if (chars.length <= columns) return String(text)",
        "  if (columns < 2) return \"\"",
        "  return chars.slice(0, columns - 1).join(\"\") + \"\\u2026\"",
        "}",
        "",
    ]
    Path(args.out).write_text("\n".join(lines))
    print(f"{len(table)} glyphs from {path.name}; {len(set(clipped))} reach outside their seven columns: "
          f"{[hex(c) for c in sorted(set(clipped))[:12]]}")


if __name__ == "__main__":
    main()
