-- Generated by tools/gen_themes.py: borders and gaps in whole virtual pixels
-- (2 logical pixels each), square corners, and no motion.
local active_border_color = "rgb(222a1c)"
local inactive_border_color = "rgb(6c765e)"

hl.config({
  general = {
    border_size = 2,
    gaps_in = 4,
    gaps_out = 8,

    col = {
      active_border = active_border_color,
      inactive_border = inactive_border_color,
    },
  },

  group = {
    col = {
      border_active = active_border_color,
      border_inactive = inactive_border_color,
    },
  },

  decoration = {
    rounding = 0,
    shadow = { enabled = false },
    blur = { enabled = false },
  },

  animations = {
    enabled = false,
  },
})
